133 srahim dev
WindhoverLabs/airliner pull request #156
Opened 2022-07-28 19:03 UTC by shahedrahim

2022-07-29 16:23 UTC, lorenzo-gomez-windhover approved these changes
LGTM!

2022-08-10 15:41 UTC, mbenson1 requested changes

2022-08-10 15:41 UTC, mbenson1 commented on core/base/tools/commander/param_csv_config.yaml
>    exportParameterValues
What is the purpose of this file?  Is this to serve as a sample input file, could you add comments as such?

2022-08-10 15:41 UTC, mbenson1 commented on core/base/tools/commander/params_to_csv.py
>  import argparse
Add comments to this file describing what the code is doing, why, and how.

2022-08-15 20:20 UTC, shahedrahim commented on core/base/tools/commander/param_csv_config.yaml
>    exportParameterValues
The file:
core/base/tools/commander/README.md
describes the purpose of the yaml file.  It is the file needed to configure the params pulled from YAMCS.

2022-08-15 20:38 UTC, shahedrahim commented on core/base/tools/commander/params_to_csv.py
>  import argparse
Added Comments in code

2022-08-15 20:40 UTC, shahedrahim reviewed
New changes on branch address comments made by reviewer.

2022-08-15 20:46 UTC, shahedrahim commented on core/base/tools/commander/params_to_csv.py
>  import argparse
fd680e96e8e9d4c0134cf825ae177ebe85931feb

2022-08-19 02:36 UTC, merged