FPC Code Review
WindhoverLabs/airliner pull request #160
Opened 2022-08-01 23:44 UTC by lorenzo-gomez-windhover

2022-08-02 16:18 UTC, lorenzo-gomez-windhover reviewed
Found issue on FPC where `m_VehicleGlobalPositionMsg.Alt` was used instead of `m_VehicleGlobalPositionMsg.Lon`. See fc37f6e47060a39291b73b25dee74df167792df5

2022-08-15 16:24 UTC, mbenson1 requested changes
This is my comment.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> + *   Copyright (c) 2017 Windhover Labs, L.L.C. All rights reserved.
Change this to 2022

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +        //TODO:Add when air speed message exists
Address this TODO

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +    memset((void*)&InData, 0x00, sizeof(InData));
"InData" was just a place holder created by the template.  Delete it.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +    /* Init output data */
Remove all the unnecessary comments and unnecessary white space.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +    memset((void*)&m_PositionControlStatusMsg, 0x00, sizeof(m_PositionControlStatusMsg));
You don't need to "memset" these first.  The "TRUE" argument below does this.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +    CFE_SB_InitMsg(&m_PX4_TecsStatusMsg,
Fix the unnecessary line feeds.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +        iStatus = CFE_SB_Subscribe(FPC_CMD_MID, CmdPipeId);
Change this to CFE_SB_SubscribeEx with the Message Limit build time configurable.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +    CFE_PSP_MemSet(&m_ManualControlSetpointMsg, 0, sizeof(m_ManualControlSetpointMsg));
Add boolean flags that indicate a message has ever been received.  You're going to add code later that ensures you only act on the message IF the message has ever been received.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +	{
Run this through a code formatter.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +                UpdateParamsFromTable();
This function should probably not exist... Probably.  This suggests we are basically copying parameters out of a table.  Use the table directly.  Don't copy them out to use them.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +                    CFE_PSP_MemCpy(&m_AirspeedMsg, dataMsgPtr, sizeof(m_AirspeedMsg));
Did we ever actually subscribe to this?  Check a "TODO" from above.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +                /* TODO:  Add code to process other subscribed commands here
Remove this TODO

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +            ConfigTblPtr->LND_TLALT = 0.66f * ConfigTblPtr->LND_FLALT;
Don't change config parameters here.  This is a big no-go.  If that needs to be "0.66f * ConfigTblPtr->LND_FLALT" then the table should have been initialized with "0.66f * LND_FLALT".  Parameters should be mostly read only.  The only exception is for ground commands that are specifically designed to change table parameters.  There's also an extra step required when you do change table parameters.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +        ConfigTblPtr->PSP_OFF_RADIANS = ConfigTblPtr->PSP_OFF_RADIANS;
Why?

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +            ConfigTblPtr->LND_TLALT = 0.66f * ConfigTblPtr->LND_FLALT;
Don't change table parameters.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +            case FPC_NOOP_CC:
The template code forgot to generate code that verifies the command byte length.  Call VerifyCmdLength for each command.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +    CFE_PSP_MemCpy(&HkTlm._hdg_hold_curr_wp, &_hdg_hold_curr_wp, sizeof(_hdg_hold_curr_wp));
Why don't you just delete the "_hdg_hold_curr_wp" structure from the class and just use the one in "HkTlm._hdg_hold_curr_wp".  In other words, why do we have two copies of the same data?

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +    int32 iStatus = CFE_SB_SendMsg((CFE_SB_Msg_t*)&OutData);
"OutData" was just place holder code created by the template.  You were supposed to either tailor that "OutData" to something more specific, or just delete it.  You've already added your specific messages, so just delete "OutData" entirely.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +            m_Hold_Alt += m_VehicleGlobalPositionMsg.DeltaAlt;
This should be protected by code that ensures this only executes WHEN the "ControlAltitudeEnabled" flag transitions from false to true.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +        if (m_VehicleControlModeMsg.ControlAltitudeEnabled && (m_VehicleGlobalPositionMsg.AltResetCounter != m_Alt_Reset_Counter)) {
The "AltResetCounter" is boolean, right?  The problem is this requires that the VehicleGlobalPosition publisher and FPC run at the same rate.  This is because "AltResetCounter" may only be true for a single minor frame.  If the message gets dropped or FPC does not run in this frame, that "true" flag will get missed.  If, however, this was an uint32 that increments when the "AltResetCounter" should occur, FPC does not need to execute at the same rate.  It can run totally independently and be resilient to drop out.  Then, if the "AltResetCounter" has CHANGED, it knows it must perform the action that the "AltResetCounter == true" requires.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +//    if(LastProcessed != this->m_AirspeedMsg.Timestamp)
Why is this commented out?  It looks like this is another example of something that should only happen when a new message has arrived.  It looks like this should only happen when the AirspeedMsg is fresh.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +
Remove all this unnecessary whitespace.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +        float turn_distance = _l1_control.switch_distance(500.0f);
500.0f = magic number

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +        if ((PX4LIB_GetPX4ElapsedTimeUs(m_PositionControlStatusMsg.Timestamp) > 1000000)
Why "1000000"?

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +    uint64 delta_takeoff = 10000000;
Magic number.  And why 10s?

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +        if (m_VehicleControlModeMsg.ControlAltitudeEnabled && (m_VehicleGlobalPositionMsg.AltResetCounter != m_Alt_Reset_Counter)) {
Its not.  "AltResetCounter" is a counter, so it appears this was written correctly in the reference code.  Problem is, I don't see where this counter is every incremented.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +            m_Hold_Alt += m_VehicleGlobalPositionMsg.DeltaAlt;
Now, I think this is protected.  By the AltResetCounter check.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +//    if(LastProcessed != this->m_AirspeedMsg.Timestamp)
Nope.  I think this is correct.  Just clean up the code by deleting the commented out lines.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +    math::Vector2F curr_pos(m_VehicleGlobalPositionMsg.Lat, m_VehicleGlobalPositionMsg.Alt);
This is incorrect.  Check the reference code.  Line 1607.  ".Alt" should be ".Lon".

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +        if ((PX4LIB_GetPX4ElapsedTimeUs(m_PositionControlStatusMsg.Timestamp) > 1000000)
Revisit this patterns and replace them with scheduled activities.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +
The reference code publishes the fw_pos_ctrl_status message here.

2022-08-15 16:24 UTC, mbenson1 commented on apps/fpc/fsw/src/fpc_app.cpp
> +        if (!ConfigTblPtr->ARSP_MODE) {
The reference code only performs the action when the Airspeed message is fresh.  The "_sub_airspeed.updated()" function returns true if the message has changed since the last time the message was called.  Beware of these "<subscription>.updated()" functions.

2022-08-15 16:24 UTC, mbenson1 commented on apps/amc/fsw/src/amc_app.h
> -    /** \brief PWM Config Table Handle */
What is this?

2022-08-15 19:29 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> + *   Copyright (c) 2017 Windhover Labs, L.L.C. All rights reserved.
Resolved in a1bb75422285a0de935a48ea75b1cdedb295baf7

2022-08-15 19:43 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +        //TODO:Add when air speed message exists
Fixed in f08c1f1383a583802e012e706607a68a180ae861

2022-08-15 20:02 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +    memset((void*)&InData, 0x00, sizeof(InData));
Fixed in b9a1264a168281407c640723b3dedffbdeaf7fed

2022-08-15 20:02 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +    /* Init output data */
Fixed in b9a1264a168281407c640723b3dedffbdeaf7fed

2022-08-15 20:03 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +    math::Vector2F curr_pos(m_VehicleGlobalPositionMsg.Lat, m_VehicleGlobalPositionMsg.Alt);
Fixed in fc37f6e47060a39291b73b25dee74df167792df5

2022-08-15 20:12 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +    memset((void*)&m_PositionControlStatusMsg, 0x00, sizeof(m_PositionControlStatusMsg));
Fixed in 1d2feb85a6efcd3586a735b449c07d81c4b1f4de

2022-08-15 20:21 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +        iStatus = CFE_SB_Subscribe(FPC_CMD_MID, CmdPipeId);
Fixed in 854f2eb214b7d7fd687901aa0af8cfe7383d4e6e

2022-08-15 20:31 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +                    CFE_PSP_MemCpy(&m_AirspeedMsg, dataMsgPtr, sizeof(m_AirspeedMsg));
Yes we did: https://github.com/WindhoverLabs/airliner/blob/854f2eb214b7d7fd687901aa0af8cfe7383d4e6e/apps/fpc/fsw/src/fpc_app.cpp#L279

2022-08-15 20:43 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +                /* TODO:  Add code to process other subscribed commands here
Fixed in e7e3ae59f302c698b40018f652c8c0130b6a4fef

2022-08-15 21:15 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +        ConfigTblPtr->PSP_OFF_RADIANS = ConfigTblPtr->PSP_OFF_RADIANS;
No reason other than missed that one. Fixed in a9e526fb7253a5360f56bfe791d44aa1c445e5e7

2022-08-15 21:50 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +            case FPC_NOOP_CC:
Fixed in 0c7c6e88b182aa3d4782310f635577e05d9bdb4d

2022-08-15 22:01 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +    CFE_PSP_MemCpy(&HkTlm._hdg_hold_curr_wp, &_hdg_hold_curr_wp, sizeof(_hdg_hold_curr_wp));
You're right. It's redundant with no benefit at all. Fixed in e5565114891fda921d07456dc76ed37c0ce68e5b.

2022-08-15 22:06 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +    int32 iStatus = CFE_SB_SendMsg((CFE_SB_Msg_t*)&OutData);
Fixed in 5eca83f7afd407686f17622a035b79b0b5b8c8c9

2022-08-15 22:09 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +
Fixed in cc1225ea335e9b0568b56eec42cf7829892b006f

2022-08-15 22:13 UTC, lorenzo-gomez-windhover commented on apps/fpc/fsw/src/fpc_app.cpp
> +    CFE_SB_InitMsg(&m_PX4_TecsStatusMsg,
Fixed in 26978d2c71bf5c8d4ca564ca68e9b5674526984d

2022-08-16 21:21 UTC, merged