207 unit test for amc app
WindhoverLabs/airliner pull request #224
Opened 2022-10-03 21:06 UTC by ynielson

Ready to be merged.(Checked issue ticket and resolved)

2022-11-08 19:05 UTC, mbenson1 requested changes

2022-11-08 19:05 UTC, mbenson1 commented on apps/amc/fsw/unit_test/amc_config_tbl_test.cpp
> +    sprintf(expectedEvent, "Failed to register config table (0x%08X)", (unsigned int)expected);
Good job!  I am VERY happy to see you use this pattern unprompted.  This is exactly the patterns that you should use.  Use this pattern throughout.  By using the macro to dynamically create the expected text, you have decoupled the unit test from the error value.  My only recommendation is to use this more for the configurable parameters like message IDs and perf IDs.  Error IDs are not configurable and are set at design time.  Decoupling the string from design time parameters is still useful since it makes the unit test less sensitive to CFE version change.

2022-11-08 19:05 UTC, mbenson1 commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    printf("###UpdateMotors_SendMsgHook: MsgLen(%u)\n", msgLen);
Why is this here?  If this is no longer necessary, remove it.  If this is to assist future debugging should a unit test fail, I will allow it.

2022-11-08 19:05 UTC, mbenson1 commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    DataPipe = Ut_CFE_SB_CreatePipe("AMC_DATA_PIPE");
Replace that hard coded string with the macro that is in the platform or mission configuration file.  Always use the macros and never hard code configuration parameters.

2022-11-08 19:05 UTC, mbenson1 commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    oAMC.AppMain();
Where is the test case?  This is a good setup, but there is no actual test case.  Looks like you forgot it.  But good setup though.

2022-11-08 19:05 UTC, mbenson1 commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    oAMC.AppMain();
No test case.

2022-11-08 19:05 UTC, mbenson1 commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    AMC  oAMC;
By the way, this is a great use of the C++ patterns to assist with unit testing.  By allocating the object in the function call and on the call stack, you are sort of clearing the object before every execution.  I don't know if you thought of this specifically, but you are also injecting negative testing which is fantastic.  By allocating on the call stack, member attributes that are not explicitly set will have random data from the call stack.  Good job.

2022-11-09 14:22 UTC, ynielson commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    printf("###UpdateMotors_SendMsgHook: MsgLen(%u)\n", msgLen);
Done.

2022-11-09 15:11 UTC, ynielson commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    DataPipe = Ut_CFE_SB_CreatePipe("AMC_DATA_PIPE");
Done.

2022-11-09 15:31 UTC, ynielson commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    AMC  oAMC;
Yes I have thought of that. Specifically, I used this pattern in some of the VM app test cases too.

2022-11-09 15:32 UTC, ynielson commented on apps/amc/fsw/unit_test/amc_config_tbl_test.cpp
> +    sprintf(expectedEvent, "Failed to register config table (0x%08X)", (unsigned int)expected);
I will work on that direction.

2022-11-09 15:32 UTC, ynielson commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    oAMC.AppMain();
Working on it.

2022-11-09 15:33 UTC, ynielson commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    oAMC.AppMain();
Working on it.

2022-11-09 20:57 UTC, ynielson commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    oAMC.AppMain();
I did minor bug fix to InitDevice hook function and removed debug printf.
And I don't think I can decide PASS/FAIL to this test cases, I just printed output data to the "SetMotorOutputs" hook function  and SendMsg hook function.

2022-11-10 16:38 UTC, ynielson commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    oAMC.AppMain();
Same as the above.

2022-11-10 16:49 UTC, ynielson commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    oAMC.AppMain();
Oh, I got you what you meant, while I was going through the SENS merge request comment.
I will add test cases that can be decided in each condition.

2022-11-14 21:36 UTC, ynielson commented on apps/amc/fsw/unit_test/amc_motor_update_test.cpp
> +    oAMC.AppMain();
I updated UpdateMotors test cases based on the request.(The following conditions are checked)
 1.  No channels configured as “SAFE” in the configuration table will actuate when the vehicle is disarmed.
 2.  Channels configured as “IGNORE” in the configuration table will actuate when the vehicle is disarmed.
Updates were pushed.

2022-12-05 20:47 UTC, mbenson1 approved these changes

2022-12-05 20:47 UTC, merged